
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package json;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TkJsCOMENTUNALINEA = 9;
  public static final int TkJsDECIMAL = 6;
  public static final int EOF = 0;
  public static final int TkJsLLAVEABRE = 2;
  public static final int error = 1;
  public static final int TkJsCOMA = 5;
  public static final int TkJsCOMENTMULTI = 8;
  public static final int TkJsLLAVECIERRA = 3;
  public static final int TkJsDOSPUNTOS = 4;
  public static final int TkJsCADENA = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TkJsLLAVEABRE",
  "TkJsLLAVECIERRA",
  "TkJsDOSPUNTOS",
  "TkJsCOMA",
  "TkJsDECIMAL",
  "TkJsCADENA",
  "TkJsCOMENTMULTI",
  "TkJsCOMENTUNALINEA"
  };
}

